CREATE TABLE IF NOT EXISTS rol(
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	description VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user(
	id VARCHAR(50) NOT NULL,
	password VARCHAR(256) NOT NULL,
	rol TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (rol) REFERENCES rol(id) ON UPDATE CASCADE ON DELETE CASCADE
);